name: CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [8, 10, 12]
    steps:
      - name: Checkout the changes from Git
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          version: ${{ node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Execute tests
        run: npm test
      - name: Record code coverage
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
